development:
  clients:
    phoncol:
      database: app
      hosts:
        - localhost:27017
      options:
    default:
      database: cms_server
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    phoncol:
      database: app
      hosts:
        - 192.168.200.210:27017
        - 192.168.200.211:27017
      options:
        user: 'root'
        password: 'b6wUu2qwpXhj61Ro'
        auth_mech: :scram
        auth_source: admin
    phoncol_im:
      database: im
      hosts:
        - 192.168.200.200:27017
        - 192.168.200.201:27017
      options:
        user: 'root'
        password: 'Wzy2rq9iiHW0AuVv'
        auth_mech: :scram
        auth_source: admin
    default:
      database: cms_server
      hosts:
        - localhost:27017
      options:
  options:
# production:
